@startuml

class Item{
int: id
string: name
double: price
..
+ createItem()
+ setPrice()
}

class Inventory{
item: Items
..
+ restockInventory()
+ removeItem()
+ addItem()
+ isInStock()
}

class VendingMachine{
inventory: Inventory
..
+ isValidInput()
+ isPaidInFull()
+ issueRefund()
+ isUnderPaid()
}

class NotEnoughCash{
string: errorMessage
double: missingAmount
..
+ throwMessage()
}

class InvalidInput{
string: errorMessage
string: inputName
double: paymentAmount
..
+ throwMessage()
}

class OutOfStock{
string: errorMessage
item: Item
..
+ throwMessage()
}

Inventory <-- Item
VendingMachine <-- Inventory

OutOfStock <-- Inventory
NotEnoughCash <-- VendingMachine
InvalidInput <-- VendingMachine
@enduml
